trailingComma: 'es5'
singleQuote: true
#
overrides:
  - files: 'dist/**'
    options:
      trailingComma: 'none'
      arrowParens: 'avoid'
  - files: 'dist/**/bin/!(*.*)'
    options:
      parser: 'babel'
    #
  - files: 'dist/**/index.js'
    options:
      useTabs: true
  - files: 'dist/**/tape'
    options:
      printWidth: 110
