trailingComma: 'es5'
singleQuote: true
#
overrides:
  - files: 'dist/**'
    options:
      trailingComma: 'none'
      arrowParens: 'avoid'
  - files: 'dist/**/bin/*'
    options:
      parser: 'babel'
    #
  - files: 'dist/**/loader-utils.js'
    options:
      dedentSwitchLabels: true
  - files: 'dist/**/loader-utils.js'
    options:
      preserveQuote: true
    #
  - files: 'dist/**/loader-utils.js'
    options:
      bracketSpacing: false
      arrowParens: 'always'
  - files: 'dist/**/loader-utils.js'
    options:
      printWidth: 105
