trailingComma: 'es5'
singleQuote: true
#
overrides:
  - files: 'dist/**'
    options:
      trailingComma: 'none'
      arrowParens: 'avoid'
  - files: 'dist/**/bin/!(*.*)'
    options:
      parser: 'babel'
    #
  - files: 'dist/**/lockfile.js'
    options:
      preserveQuote: true
  - files: 'dist/**/{lockfile,cli}.js'
    options:
      trailingComma: 'es5'
      bracketSpacing: false
      printWidth: 115
