trailingComma: 'es5'
singleQuote: true
#
overrides:
  - files: 'dist/**'
    options:
      trailingComma: 'none'
      arrowParens: 'avoid'
  - files: 'dist/**/bin/!(*.*)'
    options:
      parser: 'babel'
    #
  - files: 'dist/**/{lockfile,acorn,vendors}.js'
    options:
      preserveQuote: true
  - files: 'dist/**/{lockfile,cli,acorn,v8-*,vendors}.js'
    options:
      bracketSpacing: false
  - files: 'dist/**/{cli,acorn,v8-*,vendors}.js'
    options:
      spaceAfterAnonFunc: false
    #
  - files: 'dist/**/preinstall.js'
    options:
      tabWidth: 4
  - files: 'dist/**/{lockfile,cli,preinstall,v8-*}.js'
    options:
      trailingComma: 'es5'
      printWidth: 115
  - files: 'dist/**/cli.js'
    options:
      printWidth: 120
  - files: 'dist/**/acorn.js'
    options:
      singleQuote: false
      dedentSwitchLabels: true
      printWidth: 135
  - files: 'dist/**/v8-compile-cache.js'
    options:
      printWidth: 89
  - files: 'dist/**/vendors.js'
    options:
      printWidth: 125
